import { SSRCtx } from './type';
export let ctx: SSRCtx = {
  root: null,
  current: null
};

export const cleanCtx = () =>
  Object.keys(ctx).forEach(key => {
    ctx[key] = null;
  });

export const CONTENT_FLAG = Symbol('hasContent');
export const DELEGATED = Symbol('delegated');
export const BOBE_MEMO = Symbol('bobeMemo');
export const BOBE_EVENT = '__BOBE_EVENT_';



export const BOOLEAN_ATTRS = new Set([
  'disabled',
  'readonly',
  'checked',
  'selected',
  'hidden',
  'multiple',
  'required',
  'autofocus',
  'autoplay',
  'controls',
  'loop',
  'muted',
  'defer',
  'async',
  'reversed',
  'open',
  'itemscope',
  'ismap',
  'nohref',
  'noshade',
  'nowrap',
  'compact',
  'default'
]);

export const VALUE_PROP_TAGS = new Set(['INPUT', 'TEXTAREA', 'SELECT']);

export const SVG_NS = 'http://www.w3.org/2000/svg';
export const MATH_NS = 'http://www.w3.org/1998/Math/MathML';

export const SVG_TAGS = new Set([
  'svg',
  'animate',
  'animateMotion',
  'animateTransform',
  'circle',
  'clipPath',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'metadata',
  'mpath',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'set',
  'stop',
  'switch',
  'symbol',
  'textPath',
  'tspan',
  'use',
  'view'
]);

export const MATH_TAGS = new Set([
  'math',
  'maction',
  'maligngroup',
  'malignmark',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mglyph',
  'mi',
  'mlabeledtr',
  'mlongdiv',
  'mmultiscripts',
  'mn',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'ms',
  'mscarries',
  'mscarry',
  'msgroup',
  'mstack',
  'mspace',
  'msqrt',
  'msrow',
  'mstyle',
  'msub',
  'msup',
  'msubsup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
  'semantics',
  'annotation',
  'annotation-xml'
]);

export const NON_DELEGATED_EVENTS = new Set([
  'abort',
  'blur',
  'cancel',
  'close',
  'cuechange',
  'error',
  'focus',
  'invalid',
  'load',
  'mouseenter',
  'mouseleave',
  'pointerenter',
  'pointerleave',
  'resize',
  'scroll',
  'scrollend',
  'selectionchange',
  'toggle',
  'beforetoggle',
  'canplay',
  'canplaythrough',
  'durationchange',
  'emptied',
  'ended',
  'loadeddata',
  'loadedmetadata',
  'loadstart',
  'pause',
  'play',
  'playing',
  'progress',
  'ratechange',
  'seeked',
  'seeking',
  'stalled',
  'suspend',
  'timeupdate',
  'volumechange',
  'waiting'
]);